// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.SmsSender.Postgres;

namespace Service.SmsSender.Postgres.Migrations
{
{
    [DbContext(typeof(SmsSenderDbContext))]
    [Migration("20210306104651_ver_0")]
    partial class ver_0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smssender")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Service.SmsSender.Postgres.SmsHistoryEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("MaskedPhone")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("Template")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Provider")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("ProcDate")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("ProcError")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("ClientId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.ToTable("sent_history");
            });
#pragma warning restore 612, 618
        }
    }
}